#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" XMLModelDescBuilder
XML格式的模型描述建造者
"""

import basebuilder

import os
import re
import time
import xml.etree.cElementTree as xmllib
import xml.dom.minidom as minidom

pother = re.compile(r'^([^_]+)[_]([^_]+)[_]([^.]+)[.]xls\w*')

class XMLModelDescBuilder(basebuilder.BaseBuilder):
    def __init__(self, datamodel, folder):
        super(XMLModelDescBuilder, self).__init__(datamodel)
        if type(folder) == str:
            self.folder = os.path.abspath(folder.decode('utf-8'))
        elif type(folder) == unicode:
            self.folder = os.path.abspath(folder)
        else:
            raise TypeError("folder type (%s) is invalid!", str(type(folder)))
        
        self.outfiles = []

    def GenerateProjectRootNode(self, pj_name):
        root = xmllib.Element("Component:Component_Define", {"xmlns:Types":"http://www.appsoft.com.cn/Core/Types",
                                                                 "xsi:schemaLocation":"http://www.appsoft.com.cn/Component ../Component.xsd",
                                                                 "xmlns:Component":"http://www.appsoft.com.cn/Component",
                                                                 "xmlns:xlink":"http://www.w3.org/1999/xlink",
                                                                 "xmlns:xsi":"http://www.w3.org/2001/XMLSchema-instance"})
        comment = xmllib.Comment("Edited with Modelingtools by LMice TEAM, generated by ElementTree(Python) at: %s " % time.ctime() )
        root.append(comment)
        pnode = xmllib.SubElement(root, "Project", {"Id":pj_name, "Name":pj_name, "Language":"C++"})
        xmllib.SubElement(pnode, "Description")
        return root

    def GenerateProjectImport(self, pj_name, root):

        if not self.reftypes.has_key(pj_name):
            return
        imports = {}
        tlist = self.reftypes[pj_name]

        for id in tlist:
            namespace, name = tlist[id]
            name, namespace = self.RefineNamespace(name, namespace)
            if not imports.has_key(namespace):
                nsnode = xmllib.SubElement(root, "Import", {"Id":namespace, "Name":namespace,
                    "Location":namespace})
                imports[namespace] = nsnode
            nsnode = imports[namespace]
            xsi_type,xsi_name,xsi_ns = self.GetXsiType(name, namespace)
            xmllib.SubElement(nsnode, "Type", {"Id":"%s.%s" %(xsi_ns, xsi_name),"Name":xsi_name,
                "Uuid":self.GetTypeUuid(xsi_name, xsi_ns), "xsi:type": xsi_type })
            #detail ...

    def GenerateComponentNode(self, pj_name, root):

        com = xmllib.SubElement(root, "Component", {"type":pj_name, "category":"ModelComponent",
            "GUID": "{%s}" % self.GetTypeUuid(pj_name, "Constructive"),
                                                     "LVC_Feature":"Constructive"})
        xmllib.SubElement(com, "Inherit")
        dnode = xmllib.SubElement(com, "Description")
        xmllib.SubElement(dnode, "ChineseName").text = self.projects[pj_name][3]
        xmllib.SubElement(dnode, "EnglishName").text = pj_name
        xmllib.SubElement(dnode, "Creator").text = "Modelingtools"
        xmllib.SubElement(dnode, "Department").text = "Tsinghua"
        xmllib.SubElement(dnode, "DdevelopDate").text = time.strftime("%Y-%m-%d %H:%M:%S")
        xmllib.SubElement(dnode, "Version").text = "V1.0"

        pj_element = self.elements[pj_name]
        if pj_element.has_key("Properties"):
            com.append(pj_element["Properties"])
        if pj_element.has_key("Inputs"):
            com.append(pj_element["Inputs"])
        if pj_element.has_key("Outputs"):
            com.append(pj_element["Outputs"])
        if pj_element.has_key("ReceiveEvents"):
            com.append(pj_element["ReceiveEvents"])
        if pj_element.has_key("SendEvents"):
            com.append(pj_element["SendEvents"])

    def GenerateCompositeNode(self, pj_name, root):
        return

    def GenerateResourceNode(self, pj_name, root):
        xmllib.SubElement(root, "Resource", {"platform":"_X86_32_WIN_5_VC90", "path":"", "name":"%s.dll" % pj_name})

    def SaveDscFile(self, pj_name, root):
        doc = minidom.parseString( xmllib.tostring(root, 'utf-8') )
        data = doc.toprettyxml(encoding="utf-8")
        name = os.path.join(self.folder, u"%s.xml" % pj_name)

        f = open(name, "w")
        f.write(data)
        f.close()
        self.outfiles.append(name.encode('utf-8'))

    def ParseItemSource(self, item):
        #Get pj_name from xlfile
        pj_num = ""
        pj_name = ""
        pj_cname = ""
        xlfile = os.path.split(item.source)[1]
        lv = pother.findall(xlfile)
        if len(lv) ==1 and len(lv[0]) == 3:
            pj_num = lv[0][0]
            pj_name = lv[0][1]
            pj_cname = lv[0][2]
        #store project properties
        self.projects[pj_name] = [item.source, pj_num, pj_name, pj_cname]
        return pj_num, pj_name, pj_cname

    def GetProjectNodeByName(self, pj_name, key):
        if not self.elements.has_key(pj_name):
            self.elements[pj_name]={}
        if not self.elements[pj_name].has_key(key):
            node = xmllib.Element(key)
            self.elements[pj_name][key] = node
        return self.elements[pj_name][key]

    def CreateModelInitParamItem(self, data):
        #Get pj_name from xlfile
        pj_num, pj_name, pj_cname = self.ParseItemSource(data)
        if pj_num == "":
            return
        pps = self.GetProjectNodeByName(pj_name, "Properties")
        pp_name, pp_cname, pp_items = data.item_val[:3]
        for item in pp_items:
            for i in range(len(item)):
                if item[i] == None:
                    item[i] = ""
                if type(item[i]) == str:
                    item[i] = item[i].decode('gbk')
                elif not type(item[i]) == unicode:
                    #print type(item[i]), type(item[i]) != unicode
                    item[i] = unicode(item[i])
            it_name, it_ns, it_cname, it_type, it_grain, it_unit, it_default, it_min, it_max, it_desc = item[:10]
            pp = xmllib.SubElement(pps, "Property", {"Name":it_name, "ChineseName":it_cname})
            xmllib.SubElement(pp, "Description").text = it_desc
            #refinement namespace
            it_type, it_ns = self.RefineNamespace(it_type, it_ns)
            xmllib.SubElement(pp, "Type", {"Namespace":it_ns,"Href":it_type, "HrefUuid":self.GetTypeUuid(it_type, it_ns)})
            #TODO: what are xsi:types of user defined types
            xmllib.SubElement(pp, "Default", {"Value":it_default, "xsi:type":"Types:%sValue" % it_type})

            #update reftypes
            if not self.reftypes.has_key(pj_name):
                self.reftypes[pj_name]={}
            self.reftypes[pj_name]["%s.%s" %(it_ns, it_type)] = [it_ns, it_type]

    def CreateModelMessageItem(self, item):
        #Get pj_name from xlfile
        pj_num, pj_name, pj_cname = self.ParseItemSource(item)
        if pj_num == "":
            return

        #Create in/out Message nodes
        innode =    self.GetProjectNodeByName(pj_name, "Inputs")
        outnode =   self.GetProjectNodeByName(pj_name, "Outputs")
        parent = innode
        name = "Input"
        cp_name, cp_ns, cp_cname, cp_io, cp_desc, cp_var, cp_items = item.item_val[:7]
        cp_name, cp_ns = self.RefineNamespace(cp_name, cp_ns)
        if cp_io == u"输出":
            parent = outnode
            name = "Output"
        onode = xmllib.SubElement(parent, name, {"Name":cp_name})

        xmllib.SubElement(onode, "Type", {"Href":"%s_T" % cp_name, "HrefUuid":self.GetTypeUuid(cp_name, cp_ns),
            "Namespace":cp_ns})

        #update reftypes
        if not self.reftypes.has_key(pj_name):
            self.reftypes[pj_name]={}
        self.reftypes[pj_name]["%s.%s" %(cp_ns, cp_name)] = [cp_ns, cp_name]
    
    def CreateModelEventItem(self, item):
        #Get pj_name from xlfile
        pj_num, pj_name, pj_cname = self.ParseItemSource(item)
        if pj_num == "":
            return

        #Create in/out Event nodes
        innode =    self.GetProjectNodeByName(pj_name, "ReceiveEvents")
        outnode =   self.GetProjectNodeByName(pj_name, "SendEvents")

        parent = innode
        name = "ReceiveEvent"
        cp_name, cp_ns, cp_cname, cp_io, cp_desc, cp_var, cp_items = item.item_val[:7]
        cp_name, cp_ns = self.RefineNamespace(cp_name, cp_ns)
        if cp_io == u"输出":
            parent = outnode
            name = "SendEvent"

        onode = xmllib.SubElement(parent, name, {"Name":cp_name})
        xmllib.SubElement(onode, "Type", {"Href":"%s_T" % cp_name, "HrefUuid":self.GetTypeUuid(cp_name, cp_ns),
            "Namespace":cp_ns})

        #update reftypes
        if not self.reftypes.has_key(pj_name):
            self.reftypes[pj_name]={}
        self.reftypes[pj_name]["%s.%s" %(cp_ns, cp_name)] = [cp_ns, cp_name]

    def BuildBegin(self):
        """ 构建准备，检查构建条件以及初始化 """
        #super(XMLModelDescBuilder, self).BuildBegin()

        if not os.path.isdir(self.folder):
            raise RuntimeError("folder(%s) is not exist!" % self.folder)
        
        self.projects = {} #key:project name, value list of project property
        self.elements = {} #key:project name, value dict of {node_type:node}
        self.reftypes={} # key: project name, value: list of tuple(namespace,name)
        self.outfiles = []
    def Build(self):
        """开始构建 为每一个ModelInitParam创建一个XML对象 """
        for ns in self.GetNamespaces():
            for item in self.GetItemByNamespace(ns):
                if   item.item_type == "ModelMessage":    #模型消息
                    self.CreateModelMessageItem(item)
                elif item.item_type == "ModelInitParam":    #模型参数
                    self.CreateModelInitParamItem(item)
                elif item.item_type == "ModelEvent":    #模型事件
                    self.CreateModelEventItem(item)
                elif item.item_type == "EnumData":  # 枚举类型
                    #self.AddEnumType(item)
                    pass
                elif item.item_type == "CompData":  #复合数据结构
                    #self.AddCompType(item)
                    #print "CompData"
                    pass
                elif item.item_type == "ArrayData": #数据类型
                    #self.AddArrayType(item)
                    #print "ArrayData"
                    pass
    def BuildEnd(self):
        """写入 dsc文件 """
        for pj_name in self.elements:
            #create root node
            root = self.GenerateProjectRootNode(pj_name)
            #create import node
            self.GenerateProjectImport(pj_name, root)
            #create component node
            self.GenerateComponentNode(pj_name, root)
            #create composite node
            self.GenerateCompositeNode(pj_name, root)
            #create resource node
            self.GenerateResourceNode(pj_name, root)

            #save to dsc file
            self.SaveDscFile(pj_name, root)

    def GetFiles(self):
        return self.outfiles
